vich_uploader:
    db_driver: orm
    metadata:
        file_cache:
            dir: '%kernel.build_dir%/vich_uploader'
    mappings:
        article_image:
            uri_prefix: /images/articles
            upload_destination: '%kernel.project_dir%/public/images/articles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        attachements:
            uri_prefix: /images/attachements
            upload_destination: '%kernel.project_dir%/public/images/attachements'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
